site_name: 算法笔记
site_url: https://icstorm.top/algorithm
site_author: Ekstasis
site_description: >-
  算法笔记
repo_name: Algorithm
repo_url: https://github.com/RZYN2020/Algorithm.git

docs_dir: src
site_dir: docs

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - search:
      lang: ja
  - git-revision-date-localized
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RZYN2020/Algorithm
  analytics:
    provider: google
    property: G-N1BLV69HCP

nav:
  - 前言: "index.md"
  - leetcode-contest-355: "leetcode-contest-355"